import React from "react";
import Navigation from "@/components/Navigation";
import "./globals.css";
import { Metadata } from "next";
import GlobalProvider from "@/providers/GlobalProvider";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <GlobalProvider>
      <html>
        <body>
          <div>
            <Navigation />
          </div>
          <div>
            {children}
          </div>
        </body>
      </html>
    </GlobalProvider>
  );
}
